# Generated by Django 2.2.24 on 2022-03-23 16:47

import colorful.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0004_auto_20220323_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='background_color_header',
            field=colorful.fields.RGBColorField(blank=True, verbose_name='สีส่วน Header'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='background_color_header_panel',
            field=colorful.fields.RGBColorField(blank=True, verbose_name='สีส่วนพื้นหลังเมนูด้านบน'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='background_color_menu',
            field=colorful.fields.RGBColorField(blank=True, verbose_name='สีส่วนพื้นหลัง Menu'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='background_menu_dropdown',
            field=colorful.fields.RGBColorField(blank=True, verbose_name='สีส่วนพื้นหลังเมนูด้านข้าง'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='background_website',
            field=colorful.fields.RGBColorField(blank=True, verbose_name='สีพื้นหลังเว็ปไซต์'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='btn_color_danger',
            field=colorful.fields.RGBColorField(blank=True, verbose_name='สีปุ่มกด Danger'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='btn_color_default',
            field=colorful.fields.RGBColorField(blank=True, verbose_name='สีปุ่มกด Default'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='btn_color_primary',
            field=colorful.fields.RGBColorField(blank=True, verbose_name='สีปุ่มกด Primary'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='btn_color_success',
            field=colorful.fields.RGBColorField(blank=True, verbose_name='สีปุ่มกด Success'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='color_font_header',
            field=colorful.fields.RGBColorField(blank=True, verbose_name='สีแบบอักษร'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='font',
            field=models.CharField(blank=True, choices=[('Kanit', 'Kanit font'), ('Roboto', 'Roboto font'), ('Prompt', 'Prompt font')], max_length=100, verbose_name='แบบอักษร'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='font_size_content_title',
            field=models.IntegerField(default=23, verbose_name='ขนาดตัวอักษรส่วน Content'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='font_size_header',
            field=models.IntegerField(default=19, verbose_name='ขนาดตัวอักษรส่วน Header'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='font_size_menu',
            field=models.IntegerField(default=15, verbose_name='ขนาดตัวอักษรส่วน Menu'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='menu_text_color',
            field=colorful.fields.RGBColorField(blank=True, verbose_name='สีตัวอักษรของเมนูต่างๆ'),
        ),
    ]
