# Generated by Django 2.2.24 on 2022-03-23 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0005_auto_20220323_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='font',
            field=models.CharField(blank=True, choices=[('Ubantu', 'Ubantu font'), ('Rubik', 'Rubik font'), ('Inter', 'Inter font'), ('Mukta', 'Mukta font'), ('Kanit', 'Kanit font'), ('Roboto', 'Roboto font'), ('Prompt', 'Prompt font')], max_length=100, verbose_name='แบบอักษร'),
        ),
    ]
